_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.5
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
actor_lr:
    value: 9e-05
epsilon:
    value: 1
epsilon_decay:
    value: 0.995
epsilon_min:
    value: 0.01
gamma:
    value: 0.99
max_episodes:
    value: 2000
max_steps:
    value: 1000
memory_capacity:
    value: 10000
n_states:
    value: 3
play:
    value: false
q_lr:
    value: 9e-05
sample_batch_size:
    value: 64
target_actor_update:
    value: 10
target_q_update:
    value: 10
train:
    value: true
use_noisy:
    value: true
